# Generated by Django 2.2.6 on 2019-10-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='years',
            field=models.DateField(null=True),
        ),
    ]
