# Generated by Django 2.2.5 on 2019-10-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
