# Generated by Django 2.2.5 on 2019-10-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20191016_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
